Django_Merge/urls.py
from django.contrib import admin
from django.urls import path,include
# from unit import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('unit.urls')),
    path('polls/',include('polls.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

unit/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('category/<int:id>/',views.category_detail, name='category_detail'),
    path('category/',views.category_list, name='category_list'),
    path('login',views.login,name='login'),
    path('logout',views.log_out,name='logout'),
    path('signup',views.signup,name='signup'),
    path('tag/<int:id>/',views.tag_detail, name='tag_detail'),
    path('tag/',views.tag_list, name='tag_list'),
    path('profile/',views.user_profile,name='user_profile'),
    path('profile-detail/',views.profile_update,name='profile_update'),
]

unit/models.py
# Create your models here.

from django.conf import settings
from django.db.models.deletion import PROTECT 
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

class MyUser(AbstractUser):
    email = models.EmailField()
    phone = models.IntegerField(null=True, blank=True)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    about = models.TextField()
    designation = models.CharField(max_length=50)
    image = models.ImageField(null=True, blank=True, upload_to='users/')


class Category(models.Model):
    name = models.CharField(max_length=100)
    # field_name = models.SlugField(max_length=200, **options)
    # slug = AutoSlugField(populate_from='name', max_length=200,editable=False)
    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    # slug = AutoSlugField(populate_from='name', max_length=200,editable=False)
    def __str__(self):
        return self.name    

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True,blank=True)
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=PROTECT,null=True,blank=True)
    tag = models.ManyToManyField(Tag)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True) 
    thumbnail_image = models.ImageField(upload_to='image/',null=True,blank=True)  
    featured_image = models.ImageField(upload_to='image/',null=True,blank=True)
    # slug = AutoSlugField(populate_from='name', max_length=200,editable=False)

      

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comments(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    # slug = AutoSlugField(populate_from='name', max_length=200,editable=False)

    def __str__(self):
        return self.name

class Member(models.Model):
    Firstname = models.CharField

unit/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text','category','tag','thumbnail_image','featured_image',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('name', 'email', 'comment')


class LoginForm(forms.Form):
    email = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)


class SignUpForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ('username', 'first_name', 'last_name', 'email', 'phone',
                  'city', 'state', 'country', 'about', 'designation',)

class ProfileForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ('username','first_name', 'last_name', 'email', 'phone',
                  'image', 'city', 'state', 'country')

unit/views.py
# Create your views here.


from django.shortcuts import render
from django.utils import timezone
from .models import *
from django.shortcuts import render, get_object_or_404
from .forms import PostForm
from django.shortcuts import redirect
from .forms import PostForm, LoginForm, SignUpForm, CommentForm, ProfileForm
from django.contrib import  messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate,logout
import csv
from django.http import HttpResponse





def post_list(request):
    print(request.user)
    posts = Post.objects.filter(published_date__lte=timezone.now()).all().order_by('-published_date')
    # posts = Post.objects.all()
    return render(request, 'unit/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'unit/post_detail.html', {'post': post})


def post_detail(request, pk):
    post = Post.objects.filter(pk=pk).last()
    comment = Comments.objects.filter(post=post).all()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        new_comment = form.save(commit=False)
        new_comment.post=post
        new_comment.save()
        return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
        post = get_object_or_404(Post, pk=pk)
    return render(request, 'unit/post_detail.html', {'post': post, 'form': form, 'comments': comment})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        user = MyUser.objects.filter(id=request.user.id).last()
        if form.is_valid():
            post = form.save(commit=False)
            post.author = user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'unit/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'unit/post_edit.html', {'form': form})

def signup(request):

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            print("Validdd")
            user = form.save()
            auth_login(request, user)
            return redirect('post_list')
    else:
        form = SignUpForm()
    return render(request, 'unit/Signup.html', {'form': form})

def login(request):
    if request.user.is_authenticated:
        return redirect('post_list')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(username=email, password=password)
            if user is not None:
                auth_login(request,user)
                return redirect('post_list')
            else:
                print("Invalifddddddddddddddd")
                messages.error(request,'Invalid Credential')
                return redirect('login')
    form = LoginForm()
    return render(request, 'unit/login.html', {'form': form})

def log_out(request):
    logout(request)
    return redirect('post_list')

def category_detail(request, id):
    category = Category.objects.filter(id=id).last()
    print(category,'cccccccccccccc')
    posts = Post.objects.filter(category=category).all()
    return render(request, 'unit/post_list.html', {'posts': posts})

def category_list(request):
    categories = Category.objects.all()
    return render(request, 'unit/category_list.html', {'categories': categories})

def tag_list(request):
    tags = Tag.objects.all()
    return render(request, 'unit/tag_list.html', {'tags': tags})


def tag_detail(request, id):
    tag = Tag.objects.filter(id=id).last()
    posts = Post.objects.filter(tag__name=tag).all()
    return render(request, 'unit/tag_detail.html', {'posts': posts})


def user_profile(request):
    form = ProfileForm(None,instance=request.user)
    # print(MyUser.objects.get(request.user))
    return render(request,'unit/user_profile.html', {'form': form})    

def profile_update(request):
    form = ProfileForm(None,instance=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request,'Profile Updated')
            return redirect('post_list')
    return render(request,'unit/profile_update.html', {'form': form}) 

unit/templates/unit/Signup.html
{% extends 'unit/base.html' %}
{% block content %}
<h2>Signup</h2>
<form method="POST" enctype="multitype/form-data" class="post-form">
  {% csrf_token %}
  {% for fm in form %}
  {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}
  {% endfor %}
  {% comment %} {{form.as_p}} {% endcomment %}
  <button type="submit" class=" btn btn-secondary">Signup</button>
</form>
Already Have an account <a href="{% url 'login' %}">Login</a>
{% endblock content %}

unit/templates/unit/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Cummi blog</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'unit.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <header class="page-header">
            <!-- <div class="container"> -->
                
                <div class="d-flex">
                <h1 style= "margin-left: 5%;"><a href="/">Blog</a></h1>
                <h1 style= "margin-left: 12%;"><a href="{% url 'polls:index' %}">Polls</a></h1>
                <h1 style= "margin-left: 15%;"><a href="{% url 'category_list' %}">Category</a></h1>
                <h1 style= "margin-left: 15%;"><a href="{% url 'tag_list' %}">Tag</a></h1>

                {% if user.is_authenticated %}
                {% comment %} <h1 style= "margin-left: 15%;"><a href="{% url 'logout' %}" style= "font-size: 18pt;">Logout</a></h1> {% endcomment %}
                <div class="dropdown" style= "margin-left: 13%;"> 
                    <a class="" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        {% if request.user.image %}
                        <img alt="" width="50" height="50" style="border-radius: 50%" title="" src="{{request.user.image.url}}" data-original-title="Usuario">
                        {% endif %} </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      
                      <li><a class="dropdown-item" href="{% url 'user_profile' %}">User</a></li><hr>
                      <li><a href="{% url 'logout' %}" class="dropdown-item">Logout</a></li>
                    </ul>
                  </div>
                <a href="{% url 'post_new' %}" class="top-menu" style="margin-left:200px">
                    
                <i class="fa fa-pencil" style="font-size:24px;"></i>
                </a>
                {% else %}
                <h1 style= "margin-left: 15%;"><a href="{% url 'login' %}" style= "font-size: 18pt;">Login</a></h1>
                      <!-- </div> -->
                {% endif %}
              </div>
        </header>
        <main class="content container">
            <div class="row">
                <div class="col">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </main>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    </body>
</html>

unit/templates/unit/category_detail.html
{% extends 'unit/base.html' %}

{% block content %}
  
    <article class="post">
       
        {% if post.published_date %}
            <time class="date">
                {{ post.published_date }}
            </time>
        {% endif %}
        <a href=''>{{post.category}}<a>
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </article>
{% endblock %}

unit/templates/unit/category_list.html
{% extends 'unit/base.html' %}
{% block title %}
<title>Category</title>
{% endblock title %}
{% block content %}

<h1>Categories:</h1>
{% for category in categories %}
    <a href="{% url 'category_detail' category.id %}"><p>{{category}}</p></a>
{% endfor %} {% endblock content %}

unit/templates/unit/login.html
{% extends 'unit/base.html' %}
{% block content %}
<h2>Login</h2>
<form method="POST" enctype="multitype/form-data" class="post-form">
  {% csrf_token %} {{form.as_p}}
  <button type="submit" class="btn btn-secondary">Login</button>
</form>
<a href="{% url 'signup' %}" class="thembo"> Register here</a>

{% endblock content %}

unit/templates/unit/post_detail.html
{% extends 'unit/base.html' %}
{% load static %}
{% block content %}
    <article class="post">
        <aside class="actions">
            {% if request.user.is_authenticated  %}
            <a class="btn btn-secondary" href="{% url 'post_edit' pk=post.pk %}">
                <i class="fa fa-pencil" style="font-size:24px"></i>

             </a>
            {% endif %}
         </aside>
        {% if post.published_date %}
            <time class="date">
                {{ post.published_date }}
            </time>
        {% endif %}

        <h2>
            {% if post.thumbnail_image %}
            <img src="{{post.thumbnail_image.url}}" alt="thumnial_image" width="50" height="50" style="border-radius: 50%"/>
            {% endif %}
            {{ post.title }}
            
        </h2>
        {% if post.tag %} Tag:
        {% for tag in post.tag.all %}
            <a href="{% url 'tag_detail' id=tag.id %}">{{tag}},</a>
       {% endfor %}
       {% endif %}
        {% if post.featured_image %}
        <img src="{{post.featured_image.url}}" alt="featured_image" width="100%" height="400"/>
        {% endif %}

        <p>{{ post.text|linebreaksbr }}</p>
    </article>

    {% comment %} {% for comment in comments %} {% if comment %}

    <p>{{comment.name}}:</p>
    <p>{{comment.comment|linebreaks}}</p> {% endcomment %}
    
<h2>Leave a Comment</h2>
<form method="POST" enctype="multitype/form-data" class="post-form">
  {% csrf_token %} {{form.as_p}}
  <div class="text-center">
    <button type="submit" class="save btn btn-secondary text-center">
      Submit
    </button>
  </div>
</form>

{% for comment in comments %} {% if comment %}

<p>{{comment.name}}:</p>
<p>{{comment.comment|linebreaks}}</p> 
{% for reply in comment.replies.all %}
<div class="bg-info ms-5 p-3 border-1 rounded mb-3">
  <p>{{reply.name}}</p>
  <p>{{reply.comment}}</p>
</div>
{% endfor %}
<h5 class="ms-5 p-3">Reply</h5>
<form action="" method="post">
  {% csrf_token %}
  <div class="ms-5 p-3">
    {{form.as_p}}
    <input type="hidden" name="reply_id" value="{{comment.id}}" />
    <input class="btn btn-primary" type="submit" value="Reply" />
  </div>
</form>
{% else %}
<h4>There are no comments</h4>
{% endif %} {% endfor %} {% endblock %}

unit/templates/unit/post_edit.html
{% extends 'unit/base.html' %}

{% block content %}
<h2>New post</h2>

    <form method="POST"  class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock content %}

unit/templates/unit/post_list.html
{% extends 'unit/base.html' %}
{% block content %}
    {% for post in posts %}
        <article class="post">
            <time class="date">
                {{ post.published_date }}
            </time>
            Category: <a href="{% url 'category_detail' post.category.id %}">{{post.category}}</a>
            <h2>
                <a href="{% url 'post_detail' pk=post.pk %}">
                    {% if post.thumbnail_image %}
                    <img src="{{post.thumbnail_image.url}}" alt="thumb_image" width="50" height="50" style="border-radius: 50%"/>
                    {% endif %}
                </a>

                <a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>
            </h2>           
             <p>{{ post.text|linebreaksbr|truncatechars:300}}</p>
             
              {% if post.tag %} Tag:
             {% for tag in post.tag.all %}
                 <a href="{% url 'tag_detail' id=tag.id %}">{{tag}},</a>
            {% endfor %}
            {% endif %}
       
     </article>
      {% endfor %}        

    {% endblock %}

unit/templates/unit/tag_detail.html
{% extends 'unit/base.html' %}
{% block content %}

{% for post in posts %}
    <article class="post">
        <time class="date">
            {{ post.published_date }}
        </time>
        <a href="{% url 'category_detail' post.category.id %}"><p>{{post.category}}</p></a>
        <h2><a href="{% url 'post_detail' pk=post.id %}">{{ post.title }}</a></h2>
        <p>{{ post.text|linebreaksbr }}</p>
       {% comment %} {% for tag in post.tag.all %}
        <a href="{% url 'tag_detail' pk=tag.id %}">{{tag.name}}</a>
        {% endfor %} {% endcomment %}
    </article>
{% endfor %}
{% endblock content %}

unit/templates/unit/tag_list.html
{% extends 'unit/base.html' %}
{% block title %}
<title>Tag</title>
{% endblock title %}
{% block content %}

{% for tag in tags %}
    <a href="{% url 'tag_detail' id=tag.id %}">{{tag}}</a> <br>
{% endfor %}
{% endblock content %}